#!/bin/bash
echo "🚀 Railway手動部署腳本"
echo "================================"
echo ""
echo "1. 前往 Railway 官網: https://railway.app"
echo "2. 登入並點擊 'New Project'"
echo "3. 選擇 'Deploy from GitHub repo'"
echo "4. 選擇倉庫: chatscai10/restaurant-review-system"
echo "5. 等待自動部署..."
echo ""
echo "環境變數設定:"
echo "NODE_ENV=production"
echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable"
echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true"
echo "TELEGRAM_BOT_TOKEN=7659930552:AAF_jF1rAXFnjFO176-9X5fKfBwbrko8BNc"
echo "TELEGRAM_CHAT_IDS=-1002658082392"
echo "PORT=3003"
echo ""
echo "部署完成後請提供URL進行測試"
